import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import type { PokemonResult } from '@features/challenge/types/pokemonTypes';

/**
 */
export const pokemonApiSlice = createApi({
    reducerPath: 'pokemonApi',
    baseQuery: fetchBaseQuery({ baseUrl: 'https://pokeapi.co/api/v2/pokemon' }),
    endpoints: (builder) => ({

        getPokemon: builder.query<PokemonResult, string>({
            query: (nextUrl) => nextUrl
        })
    })
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { useGetPokemonQuery } = pokemonApiSlice;
