import { createSlice, type PayloadAction } from '@reduxjs/toolkit';
import type { Pokemon } from '@features/pokemon/types/pokemonTypes';

type DeckState = Record<string, Pokemon>;

export const initialDeckState: DeckState = {};

/**
 */
export const pokemonDeckSlice = createSlice({
    name: 'pokemonDeck',
    initialState: initialDeckState,
    reducers: {
        pokemonSelected: (state, { payload }: PayloadAction<Pokemon>) => {
            if (!state[payload.name]) {
                state[payload.name] = payload;
            }
        },
        pokemonDeselected: (state, { payload }: PayloadAction<Pokemon>) => {
            if (state[payload.name]) {
                delete state[payload.name];
            }
        }
    }
});

// Redux actions automatically generated by redux toolkit
export const { pokemonSelected, pokemonDeselected } = pokemonDeckSlice.actions;
