import { createSlice, type PayloadAction } from '@reduxjs/toolkit';

type SearchState = {
    searchTerm: string;
};

const initialSearchState: SearchState = {
    searchTerm: ''
};

/**
 * Used to maintain the string value that the user searched for.
 * This allows it to be easily shared across components.
 */
const searchSlice = createSlice({
    name: 'search',
    initialState: initialSearchState,
    reducers: {
        termSearched: (state, action: PayloadAction<string>) => {
            state.searchTerm = action.payload;
        }
    }
});

// Redux actions automatically generated by redux toolkit
export const { termSearched } = searchSlice.actions;

export default searchSlice;
